print('-' * 35)
print('Tugas 1 SISOP Kelas-A')
print('-' * 35)
print('Nama : Firly Setya Wardani')
print('Npm : 21083010093')
print('-' * 35)
print('notes: ')
print('Halo Dunia!')
print('Ini adalah skrip Bash pertamaku di Linux')
